//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public short ID_CONTRATO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string DESCRIPCION_CONTRATO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public short EMPRESA_ID_EMPRESA { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
