//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_EMPRESA
    {
        public string ID { get; set; }
        public short EMPRESA_ID_EMPRESA { get; set; }
        public short SECCION_ID_SECCION { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual SECCION SECCION { get; set; }
    }
}
