//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public decimal ID_ROL { get; set; }
        public string NOMBRE_FUNCIONARIO { get; set; }
        public string RUT_FUNCIONARIO { get; set; }
        public string ROL1 { get; set; }
        public string CORREO { get; set; }
    }
}
