//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA_AREA
    {
        public long ID_TAREA_AREA { get; set; }
        public long AREA_ID_AREA { get; set; }
        public long TAREA_ID_TAREA { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual TAREA TAREA { get; set; }
    }
}
