//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USU
    {
        public USU()
        {
            this.TIPO_US = new HashSet<TIPO_US>();
        }
    
        public short ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public short EMPRESA_ID_EMPRESA { get; set; }
        public string TIPO_USUARIO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<TIPO_US> TIPO_US { get; set; }
    }
}
