//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public AREA()
        {
            this.ORDEN = new HashSet<ORDEN>();
            this.TAREA_AREA = new HashSet<TAREA_AREA>();
        }
    
        public long ID_AREA { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        public virtual ICollection<TAREA_AREA> TAREA_AREA { get; set; }
    }
}
