//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
            this.DET_EMPRESA = new HashSet<DET_EMPRESA>();
            this.FUNCIONARIO = new HashSet<FUNCIONARIO>();
            this.USU = new HashSet<USU>();
        }
    
        public short ID_EMPRESA { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public int RUN_CLIENTE { get; set; }
        public int DV_CLIENTE { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string EMAIL { get; set; }
        public int NUMERO_CELULAR { get; set; }
    
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        public virtual ICollection<DET_EMPRESA> DET_EMPRESA { get; set; }
        public virtual ICollection<FUNCIONARIO> FUNCIONARIO { get; set; }
        public virtual ICollection<USU> USU { get; set; }
    }
}
