//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public FUNCIONARIO()
        {
            this.ORDEN = new HashSet<ORDEN>();
            this.TAR_FUNC = new HashSet<TAR_FUNC>();
        }
    
        public long ID_FUNCIONARIO { get; set; }
        public string NOMBRE { get; set; }
        public string EMAIL { get; set; }
        public short EMPRESA_ID_EMPRESA { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        public virtual ICollection<TAR_FUNC> TAR_FUNC { get; set; }
    }
}
