//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class GestionDeTareas : DbContext
    {
        public GestionDeTareas()
            : base("name=GestionDeTareas")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AREA> AREA { get; set; }
        public DbSet<CONTRATO> CONTRATO { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<DET_EMPRESA> DET_EMPRESA { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public DbSet<ORDEN> ORDEN { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SECCION> SECCION { get; set; }
        public DbSet<SUBDEPTO> SUBDEPTO { get; set; }
        public DbSet<TAR_FUNC> TAR_FUNC { get; set; }
        public DbSet<TAREA> TAREA { get; set; }
        public DbSet<TAREA_AREA> TAREA_AREA { get; set; }
        public DbSet<TIPO_US> TIPO_US { get; set; }
        public DbSet<USU> USU { get; set; }
    
        public virtual int SP_AGREGAR_ROL(string nOMBRE_FUNCIONARIO, string rUT_FUNCIONARIO, string rOL, string cORREO)
        {
            var nOMBRE_FUNCIONARIOParameter = nOMBRE_FUNCIONARIO != null ?
                new ObjectParameter("NOMBRE_FUNCIONARIO", nOMBRE_FUNCIONARIO) :
                new ObjectParameter("NOMBRE_FUNCIONARIO", typeof(string));
    
            var rUT_FUNCIONARIOParameter = rUT_FUNCIONARIO != null ?
                new ObjectParameter("RUT_FUNCIONARIO", rUT_FUNCIONARIO) :
                new ObjectParameter("RUT_FUNCIONARIO", typeof(string));
    
            var rOLParameter = rOL != null ?
                new ObjectParameter("ROL", rOL) :
                new ObjectParameter("ROL", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGAR_ROL", nOMBRE_FUNCIONARIOParameter, rUT_FUNCIONARIOParameter, rOLParameter, cORREOParameter);
        }
    
        public virtual int SP_AGREGAR_TAREA(string pRIORIDAD, string nOMBRE_TAREA, string dESCRIPCION_TAREA, Nullable<System.DateTime> fECHA_INI, Nullable<System.DateTime> fECHA_TER, string nOMBRE_RESPONSABLE)
        {
            var pRIORIDADParameter = pRIORIDAD != null ?
                new ObjectParameter("PRIORIDAD", pRIORIDAD) :
                new ObjectParameter("PRIORIDAD", typeof(string));
    
            var nOMBRE_TAREAParameter = nOMBRE_TAREA != null ?
                new ObjectParameter("NOMBRE_TAREA", nOMBRE_TAREA) :
                new ObjectParameter("NOMBRE_TAREA", typeof(string));
    
            var dESCRIPCION_TAREAParameter = dESCRIPCION_TAREA != null ?
                new ObjectParameter("DESCRIPCION_TAREA", dESCRIPCION_TAREA) :
                new ObjectParameter("DESCRIPCION_TAREA", typeof(string));
    
            var fECHA_INIParameter = fECHA_INI.HasValue ?
                new ObjectParameter("FECHA_INI", fECHA_INI) :
                new ObjectParameter("FECHA_INI", typeof(System.DateTime));
    
            var fECHA_TERParameter = fECHA_TER.HasValue ?
                new ObjectParameter("FECHA_TER", fECHA_TER) :
                new ObjectParameter("FECHA_TER", typeof(System.DateTime));
    
            var nOMBRE_RESPONSABLEParameter = nOMBRE_RESPONSABLE != null ?
                new ObjectParameter("NOMBRE_RESPONSABLE", nOMBRE_RESPONSABLE) :
                new ObjectParameter("NOMBRE_RESPONSABLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGAR_TAREA", pRIORIDADParameter, nOMBRE_TAREAParameter, dESCRIPCION_TAREAParameter, fECHA_INIParameter, fECHA_TERParameter, nOMBRE_RESPONSABLEParameter);
        }
    
        public virtual int SP_AGREGAR_USU(string nOMBRE_USUARIO, Nullable<decimal> cONTRASENA, Nullable<decimal> tIPO_USUARIO)
        {
            var nOMBRE_USUARIOParameter = nOMBRE_USUARIO != null ?
                new ObjectParameter("NOMBRE_USUARIO", nOMBRE_USUARIO) :
                new ObjectParameter("NOMBRE_USUARIO", typeof(string));
    
            var cONTRASENAParameter = cONTRASENA.HasValue ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(decimal));
    
            var tIPO_USUARIOParameter = tIPO_USUARIO.HasValue ?
                new ObjectParameter("TIPO_USUARIO", tIPO_USUARIO) :
                new ObjectParameter("TIPO_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGAR_USU", nOMBRE_USUARIOParameter, cONTRASENAParameter, tIPO_USUARIOParameter);
        }
    
        public virtual int SP_LISTAR_TAREA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LISTAR_TAREA");
        }
    }
}
