//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBDEPTO
    {
        public SUBDEPTO()
        {
            this.SECCION = new HashSet<SECCION>();
        }
    
        public short ID_SUBDEPTO { get; set; }
        public string NOM_SUBDEPTO { get; set; }
        public short ID_SECCION { get; set; }
    
        public virtual ICollection<SECCION> SECCION { get; set; }
    }
}
