//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        public TAREA()
        {
            this.TAR_FUNC = new HashSet<TAR_FUNC>();
            this.TAREA_AREA = new HashSet<TAREA_AREA>();
        }
    
        public long ID_TAREA { get; set; }
        public string NOMBRE_TAREA { get; set; }
        public string DESCRIPCION_TAREA { get; set; }
        public System.DateTime FECHA_INI { get; set; }
        public System.DateTime FECHA_TER { get; set; }
        public string PRIORIDAD { get; set; }
        public string NOMBRE_RESPONSABLE { get; set; }
    
        public virtual ICollection<TAR_FUNC> TAR_FUNC { get; set; }
        public virtual ICollection<TAREA_AREA> TAREA_AREA { get; set; }
    }
}
