//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_US
    {
        public short ID_TIPO_USUARIO { get; set; }
        public string DESC_TIPO { get; set; }
        public short USU_ID_USUARIO { get; set; }
    
        public virtual USU USU { get; set; }
    }
}
